# This is a basic workflow to help you get started with Actions

name: E2E Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    # Include [noga] in the commit message to skip this expensive action
    if: ${{ !contains( github.event.head_commit.message, '[noga]' ) }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Docker pull the singleuser image for the dockerspawner tests
      run: docker pull ideonate/containds-all-basic:latest

    # Run e2e tests
    - name: Run all tests
      run: cd e2e && ./run_all.sh
      env:
        E2E_STAGES: localprocess localprocess12
        # Hide tljh for now

    - name: Save Cypress screenshots and videos
      if: ${{ success() }} || ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: e2e-cypress
        path: |
          e2e/cypress/screenshots/
          e2e/cypress/videos/
