name: Get latest release version of Z2JH
on:
# Stop cron because we don't want to pick up JupyterHub 2.x Helm Charts
#  schedule:
#    - cron:  '0 10 * * *'
  workflow_dispatch:
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/jupyterhub/zero-to-jupyterhub-k8s/releases/latest | \
          jq -r ".tag_name" > helm-z2jh-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git add helm-z2jh-latest.txt
          git config --global user.name 'Dan Lester'
          git config --global user.email 'dan@ideonate.com'
          git commit -m "New release version from z2jh"
          git push
